modLoader = "javafml" #mandatory
license="GPL-3.0-or-later"
loaderVersion = "[37,)"
issueTrackerURL="https://github.com/Cozary/animalia/issues"
[[mods]] #mandatory
modId = "animalia" #mandatory
version = "1.17.1-2.1.2"
displayName = "Animalia Mod" #mandatory
credits = "Thanks you for download my Mod. uwu" #optional
authors = "Cozary" #optional
description = ''' This mod add a bunch of diferents mobs, various blocks and 2 new biome!'''

[[dependencies.animalia]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animalia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.18)"
ordering = "NONE"
side = "BOTH"