modLoader = "javafml" #mandatory
license="GPL-3.0-or-later"
loaderVersion = "[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/Cozary/animalia/issues"
[[mods]] #mandatory
modId = "animalia" #mandatory
version = "1.16.5-2.1.2" #mandatory
displayName = "Animalia Mod" #mandatory
credits = "Thanks you for download my Mod. uwu" #optional
authors = "Cozary" #optional
description = ''' This mod add a bunch of diferents mobs, various blocks and 2 new biome!'''

[[dependencies.animalia]] #optional
# the modid of the dependency
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[35,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
# Here's another dependency
[[dependencies.animalia]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"